### ISSUE TITLE
Fix issue with duplicated keys for InMemoryDataSource

### ISSUE THREAD

**Issue by joselufo** [mobilejazz/harmony-typescript#10]
Reference: https://github.com/mobilejazz/harmony-reference/issues/27

**Comment by doup** [comment]
Fixed on PR #19 with the same solution as in Kotlin.

- TS version: https://github.com/mobilejazz/harmony-typescript/blob/feature/deprecate-deleteall/packages/core/src/repository/data-source/in-memory.data-source.ts#L64
- Kotlin version: https://github.com/mobilejazz/harmony-kotlin/blob/c772c759e026b13b8aa091d48af0deb1231c4e41/core/src/main/java/com/mobilejazz/harmony/kotlin/core/repository/datasource/memory/InMemoryDataSource.kt#L66

**Comment by doup** [comment]
Fixed by #19.
