### ISSUE TITLE
Update prettier/eslint to use Mobile Jazz presets

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#100]
- Add [@mobilejazz/eslint-config](https://github.com/mobilejazz/eslint-config)
- Add [@mobilejazz/prettier-config](https://github.com/mobilejazz/prettier-config)
- Configure husky properly to lint/format on each commit

**Comment by orioljp** [comment]
This issue has been moved to the following Asana task:
https://app.asana.com/0/1109863238977521/1203203232807698/f
