### ISSUE TITLE
Update linter configuration so that `any` is prohibited

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#101]
We've done [an effort to have strict typing](https://github.com/mobilejazz/harmony-typescript/pull/76), we should also avoid poor typing. Hence we need to ensure that no implicit/explicit `any` is used in our codebase.

We might need to update: https://github.com/mobilejazz/eslint-config

**We should fix this after #100.**

**Comment by orioljp** [comment]
I'm closing this task directly insted of creating an asana task because in my task about finishing this library and apply it to one of our projects I'm going to check this rule.
