### ISSUE TITLE
Remove `| undefined` on `nest` OAuth types

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#102]
We should use creation queries instead. See discussion:

> why the id is optional? IMO if we have an entity/model, this entity/model has an id. If not, that's not an entity, that just data pasted into an object. Summarizing, object creation in most cases should go through the query. Only updates can use value because that's an actual existing instance.

_Originally posted by @orioljp in https://github.com/mobilejazz/harmony-typescript/pull/76#discussion_r983999789_

**Comment by orioljp** [comment]
This issue has been moved to Asana.
https://app.asana.com/0/1109863238977521/1203172481263579
Closing it.
