### ISSUE TITLE
Refactor `OauthUserInfoMysqlDataSource` to use `RawSQLDataSource`

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#104]
> @doup Is this method needed since we already have the RawSQLDataSource? We can just use the SqlWhereQuery

_Originally posted by @orioljp in https://github.com/mobilejazz/harmony-typescript/pull/76#discussion_r983948361_

--- 

> If my last comment does not apply, at least we have the DiccionaryQuery that can be used to define column => value and have a more generic "where" function

_Originally posted by @orioljp in https://github.com/mobilejazz/harmony-typescript/pull/76#discussion_r983949510_

---

> This is prepared here but rewritten in the datasource

_Originally posted by @orioljp in https://github.com/mobilejazz/harmony-typescript/pull/76#discussion_r983959613_

**Comment by orioljp** [comment]
Closing this task because it's going to be continued in Asana:
https://app.asana.com/0/1109863238977521/1203203232807700
