### ISSUE TITLE
Improve how we load database configuration on `backend` example, create a standard solution for all the projects

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#105]
- Right now it uses the same way as in other projects
- It's quite… meh. Ideally we should have different config "objects" per environment
- Then, in [`database.data-source.ts`](https://github.com/mobilejazz/harmony-typescript/blob/99e7e88cf140661b288775de53bdbb3f0d411a65/examples/backend/src/config/database.data-source.ts) we just use those values, e.g. `host: config.host`

---

Check `mj-harvest-review` for possible pattern:
- [/docker/local/docker-compose.yml](https://bitbucket.org/mobilejazz/mj-harvest-review/src/master/docker/local/docker-compose.yml)
- [/docker/local/secrets/](https://bitbucket.org/mobilejazz/mj-harvest-review/src/master/docker/local/secrets/)
- [/src/src/config/configuration.ts](https://bitbucket.org/mobilejazz/mj-harvest-review/src/master/src/src/config/configuration.ts)

**Comment by lucianosantana** [comment]
Thanks for creating this @doup . I have[ a task from the DevOps team](https://app.asana.com/0/18913962099720/1202798424413918/f) that relates to this one. I'll take care of it.

**Comment by orioljp** [comment]
Find the follow up task in Asana. Closing this issue.
https://app.asana.com/0/1109863238977521/1203203232807702
