### ISSUE TITLE
Reconsider how we do the data mapping from the database to our entities

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#106]
Right now each project has it's own way of mapping data. So we can't guarantee that this is being done correctly. TypeORM already does some mapping, but it's not consistent and also favors `null` over `undefined`. See conversation for more info: https://github.com/mobilejazz/harmony-typescript/pull/76#discussion_r987576273

**Comment by orioljp** [comment]
Closing this task. Follow up Asana task:
https://app.asana.com/0/1109863238977521/1203203232807706
