### ISSUE TITLE
Remove `createCacheDecorator` in favor of self contained `Cached` decorator

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#107]
Right now to use the `@Cached()` decorator first a new instance must be created and then it's used. That's because we want a new cache for each class. This step can probably be omitted, and instead we can have a cache that takes into consideration the `instance` it's being called from (JS `Map` allows an instance as `key`). So, we can either:

- Have a map of maps, where the first level is the instance and the second one the method name
- Or, we can create a key by convining the instance and the method name.

Probably the best option is the first one, although it adds a level of indirection.

---

Something like this could work (right now it doesn't):

```typescript
export function Cached(): MethodDecorator {
    const cache: Map<unknown, Map<string, unknown>> = new Map();

    return function (target: unknown, propertyKey: string, descriptor: PropertyDescriptor): void {
        const method = descriptor.value;

        if (!cache.has(target)) {
            cache.set(target, new Map());
        }

        descriptor.value = function () {
            // This is guaranteed to exist as we're initialising it above
            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            const targetCache = cache.get(target)!;

            if (!targetCache.has(propertyKey)) {
                targetCache.set(propertyKey, method.apply(this));
            }

            return targetCache.get(propertyKey);
        };
    }
}
```

**Comment by orioljp** [comment]
Closing this issue. Follow up task here:
https://app.asana.com/0/1109863238977521/1203203232807708
