### ISSUE TITLE
Add testing infrastructure

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#13]
I want to add some unit-test infrastructure, my initial idea was to use [Karma](http://karma-runner.github.io/) (runner) + Jasmine or Mocha as testing library.

- I'm thinking on Karma so we can run the tests also in browser, it should be useful to test LocalStorage DataSources or similar code.
- Jasmine or Mocha, as I'm more fond on the BDD style of assertions, e.g.: `describe`, `it('should...')`, `expect(1).to.eql(1)`…

Although, maybe browser testing is nonsense? Maybe we should be happy with just mocking some parts (e.g. LocalStorage) and running everything on NodeJS-land? Maybe is there a new shiny object of worship on the ecosystem we should consider? ... like Jest?

**Comment by lucianosantana** [comment]
I like using Jest for the simplicity of having a single test runner and library in a single tool. For browser testing though we'd need another tool like Puppeteer ( which can be used with Jest, see https://jestjs.io/docs/en/puppeteer )

**Comment by doup** [comment]
From a first review it looks like it doesn't run the test code in the browser but instead it's an integration with Puppeteer (let's you control the browser). With Karma the idea is to be able to run the test code inside the browser, I think there isn't a similar solution for Jest yet.

In any case, I'll research the options.

**Comment by joselufo** [comment]
It's a good idea of adding testing to the infrastructure. 

Regarding which library/framework to use, I don't really know what's the best solution so I'll let you lead this discussion. 

I like Jest but I don't know the limitations or the issues.

**Comment by doup** [comment]
I was thinking on running the tests directly on the browser using Karma so that we can test some browser specific APIs. But I'm thinking that this might add unnecessary complexity to the tooling. Instead for testing APIs we could use API compatible Node packages like these:

- https://www.npmjs.com/package/localstorage-memory
- https://www.npmjs.com/package/fake-indexeddb

Yep, after saying it out loud, I think it's a good approach. Let's try Jest. If we really need to run the tests on the browser we could add Karma or migrate the tests there (since both support BDD style assertions).

**Comment by joselufo** [comment]
Agree, we should start simple instead of complex to avoid not doing it :D
