### ISSUE TITLE
Should we deprecate some of the Queries?

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#18]
Is my understanding that we want to favor domain specific queries instead of generic ones (e.g. `DictionaryQuery`). It would be nice if @vilanovi or @joselufo you can review the queries found here: https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/core/src/repository/query/query.ts

We can add a deprecation notice in the constructor like we're doing in #7 (`Remove deleteAll`).

cc @lucianosantana

**Comment by joselufo** [comment]
Thanks to open this issue to discuss and review the current  queries. 

I think there is a couple of changes that we should do and also some deprecations. I'll describe it here:

Changes:
- `IdsQuery<T>` should extend from KeyQuery. 

I think that as a general rule, we should always try to extend from `KeyQuery` if possible as it's the common query for the caching datasources / repositories. 

@vilanovi what do you think?

To Deprecate:
- `ObjectQuery<T>`, `ObjectsQuery<T>` and `ObjectRelationsQuery<T>`. I don't see value of this Queries and also I see it dangerous as most of this queries should be custom queries from the domain layer. 

I don't remember why we needed the `DictionaryQuery<T>` but it was something that we needed for a project, maybe @lucianosantana can give us some insights.

**Comment by joselufo** [comment]
@vilanovi  some comments?

**Comment by orioljp** [comment]
This issue has been moved to Asana.
https://app.asana.com/0/1109863238977521/1203172481263553/f
Closing it.
