### ISSUE TITLE
Remove unnecessary comments form OAuth2Server models

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-typescript#23]
`OAuth2UserModel` class contains commented code that it's not necessary, so it's just better to remove it.

`OAuth2BaseModel` contains commented code that it's not necesary, even if it's OPTIONAL in the comment we should remove as we have GIT to take a look in the future if needed.

**Comment by joselufo** [comment]
@vilanovi what is the status of this?

**Comment by orioljp** [comment]
I'm closing this task since these commented pieces of code have been removed during [Enable Strict Mode](https://github.com/mobilejazz/harmony-typescript/pull/76)
