### ISSUE TITLE
Refactor InMemory Datasource

### ISSUE THREAD

**Issue by Alex-DA** [mobilejazz/harmony-typescript#25]
It seems that we implemented one by one the InMemory Kotlin class, but for TypeScript we don't need an array and objects container, only one of them.

Related: https://github.com/mobilejazz/harmony-reference/issues/27

**Comment by orioljp** [comment]
I'm closing this issue since we want Harmony to be strict and need two stores because they have different types.

**Comment by doup** [comment]
I agree if you, although there is still value in changing to `Map` (which should also be a quick change). I've opened a new issue: https://github.com/mobilejazz/harmony-typescript/issues/109
