### ISSUE TITLE
PutDatasource values/values should be optional

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#26]
As discussed today `PutDatasource` `value`/`values` should be optional to differentiate insert & update scenarios.

**Comment by vilanovi** [comment]
This is correct. In languages where we have optional types, we always accept an optional value in the put method (however, the array of putAll can't be null, and must be always at least an empty array).

Typescript doesn't accept an optional parameter if it goes first in the array of parameters of the array, and the subsequent aren't optional. Therefore, we can't pass a `value?`, but instead just send undefined or null whenever required.

What did you have in mind?

**Comment by doup** [comment]
I suppose that in my original comment I wanted this to be able to differentiate create/update cases (not sure though). I suppose that after seeing the `PutDataSource` type definition, I though the `value/values` was required, but that's not how we use `PutDataSource`. In reality it does accept an "empty" value (`null/undefined`); and for example the mappers account for that (e.g. they don't map `null/undefined` values).

Now, I'm revisiting this because I've set a project in strict TypeScript mode ([see `strictnullchecks` rules](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#--strictnullchecks)) and it's telling me that `put()` doesn't accept `null`, and that's true as this is the current signature:

```ts
export interface PutDataSource<T> extends DataSource {
    put(value: T, query: Query): Promise<T>;
    putAll(values: T[], query: Query): Promise<T[]>;
}
```

To be able to compile code in strict mode (which gives better type guarantees) we would need to fix the types and be explicit about the signature. I think we should favor `undefined`… although I'm not 100% sure of the implications. In the `null` vs `undefined` debate looks like `undefined` is favoured:

- [TypeScript Coding Guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined): `Use undefined. Do not use null.`
- [Intent to stop using `null` in my JS code (sindresorhus)](https://github.com/sindresorhus/meta/discussions/7)
- [Opinion of JS creator](https://twitter.com/brendaneich/status/1171079812179361792?lang=en)
- [Discussion in Angular project](https://github.com/angular/angular/issues/42713)

In the case of `put()`, if `query` is required, then instead of an optional (`?`) we could use an union type:
`put(value: T | undefined, query: Query): Promise<T>;`

If `query` could be optional, then just:
`put(value?: T, query?: Query): Promise<T>;`

**Comment by lucianosantana** [comment]
I understand query is not optional and for that reason @vilanovi was proposing to _instead just send undefined or null_ .
This would fall into the first case you mentioned @doup. I agree with preferring `undefined` over `null`.

**Comment by joselufo** [comment]
`Query` must not be optional and value/values should be `optional`, `undefined`, or whatever TS feature represents this feature/type.

**Comment by doup** [comment]
@joselufo including `putAll` `values`?
Joan was stating otherwise, his opinion is that it should be an empty array.

So, which one?
- **A)**: `putAll(values: T[], query: Query): Promise<T[]>;` (favor empty array)
- **B)**: `putAll(values: T[] | undefined, query: Query): Promise<T[]>;` (values optional)

**Comment by vilanovi** [comment]
Kotlin does B, Swift does A. 

The good approach should be B. Swift will migrate.
