### ISSUE TITLE
Simplify `SQLOrderBy` and `SQLWhere` interfaces

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#48]
See: https://github.com/mobilejazz/harmony-typescript/blob/master/packages/core/src/repository/data-source/sql/raw-sql.data-source.ts

The idea is to simplify this interfaces:

- Remove `orderByParams()` & `whereParams()`
- Change signature of `orderBy` & `whereSql`, remove `dialect?: SQLDialect` in favor of `params?: SQLQueryParamComposer`
  - Btw, the method names are inconsistent
- Change `SQLQueryParamComposer` to accept values when calling `next()`

We need to think retro compatibility, maybe:

- Signal that `*Params` are deprecated (log? dockblock?)
- Remove `dialect` param. Add `getParameterSymbol` to `SQLQueryParamComposer`? This new `getParameterSymbol` should signal that its deprecated in any case. Work around this somehow.

*Or, we could just break.*

**Comment by doup** [comment]
Previous discussion: https://github.com/mobilejazz/harmony-typescript/pull/47#discussion_r535915371

> @doup doup 28 minutes ago Member
> I'm thinking that if the SQLDialect was needed for getParameterSymbol, then this signature should be simplified and just pass SQLQueryParamComposer as that's the one taking care of this now.
> 
> This would be a breaking change, we could pack it with the next(value) change.
> 
> ---
> 
> @vilanovi vilanovi 24 minutes ago Author Member
> This is an awesome idea @doup. We could remove the dupclication of logic if adding parameters in a method, and adding the SQL syntax in another.
> 
> However, we must think smart and do it in a retro-compatible way, otherwise it might break projects. Today I have to add a couple of changes to harmony-nest, and I'll think about solutions.

**Comment by vilanovi** [comment]
I think is better if we just break it and refactor old projects. RideLink will be refactored. OTP is easy refactorable. Repsol will be refactored.

**Comment by vilanovi** [comment]
Pull request: https://github.com/mobilejazz/harmony-typescript/pull/49

**Comment by vilanovi** [comment]
Everything is implemented and merged! Great work everyone.
