### ISSUE TITLE
Improve SQL error management

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-typescript#50]
Backend code is repeating the same code over and over:

```typescript
let result = await sqlInterface.query('select .... ', [params]).catch(e => { throw this.sqlDialect.mapError(e); })
```

Specifically the `catch(e => { throw this.sqlDialect.mapError(e); })` part of it. Probably, this could be integrated inside the `.query(..)` method.

This issue will be used to think about how to improve this.

**Comment by doup** [comment]
I reviewed this a couple of days ago and the thing is that `SQLInterface` doesn't know anything about the `SQLDialect`. But, the query is ran on `SQLInterface` and the error is managed by `SQLDialect`… so we need to inject it or merge these. I have given it a quick look and I've two ideas.

### Abstract `BaseSQLInterface`

- Create an abstract `BaseSQLInterface` that knows how to handle errors:
    ```typescript
    export abstract class BaseSQLInterface implements SQLInterface {
        constructor(
            private readonly dialect: SQLDialect,
        ) {}

        public abstract transaction<T>(runInTransaction: (sqlInterface: SQLInterface) => Promise<T>): Promise<T>;
        private abstract runQuery(query: string, parameters?: any[]): Promise<any>;

        query(query: string, parameters?: any[]): Promise<any> {
            return this.runQuery(query, parameters).catch(e => { throw this.dialect.mapError(e); });
        }
    }
    ```
- `typeorm/typeorm.sql.interface.ts` now needs to extends this `BaseSQLInterface` and implement `runQuery` & `transaction`. Having an abstract class enforces the dialect dependency and we guarantee that `mapError` is going to be used.
    ```typescript
    export class TypeORMSQLInterface extends BaseSQLInterface {
        constructor(
            dialect: SQLDialect,
            private readonly entityManager: EntityManager,
        ) {
            super(dialect);
        }

        private runQuery(query: string, parameters?: any[]): Promise<any> {
            return this.entityManager.query(query, parameters);
        }

        public transaction<T>(runInTransaction: (sqlInterface: SQLInterface) => Promise<T>): Promise<T> {
            return this.entityManager.transaction((entityManager: EntityManager) => {
                return runInTransaction(new TypeORMSQLInterface(entityManager));
            });
        }
    }
    ````

### Merge `SQLDialect` & `SQLInterface`

- Merge `SQLDialect` into `SQLInterface`
- Convert `core/data/*.dialect.ts` implementations to abstract classes that implement all but `query` & `transaction`
- Split `typeorm/typeorm.sql.interface.ts` into a MySQL and Postgres implementations. This creates code duplication.

---

Any other idea on how to compose these?

**Comment by joselufo** [comment]
This PR is almost 2 years old and I'm not sure if it's still relevant or not but I would say that I prefer the first option.

**Comment by orioljp** [comment]
This issue has been moved to Asana.
https://app.asana.com/0/1109863238977521/1203172481263561/f
Closing it.
