### ISSUE TITLE
Create OAuth2 library for NestJS

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-typescript#6]

**Comment by vilanovi** [comment]
Library is now uploaded and available in *@mobilejazz/harmony-nest*.

I have to apologize for not having created a pull request for this. Mostly, I had to move a tone of code and do a lot of trial and error in order to have files correctly working in the library and interacting with the final project. In this effort, I had to release multiple alpha versions of the project (currently at *0.2.0-alpha.10*). 

Now that everything is available, I want to spend some time reviewing the public interface of the library and evaluating if something can be improved. The OAuth library is available at the *packages/nest/oauth* folder ([link here](https://github.com/mobilejazz/harmony-typescript/tree/develop/packages/nest/src/oauth)). The public interface (the classes that are exposed) are listed in the index.ts file ([link here](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/index.ts)).

As an example of usage, we can see the example of **OTP Backend**. Find steps below:

## 1. Definition of the OAuth2Server instance

```typescript
// The OAuthProvider is an interface that has two methods: 
//     1. userModel(): used for password, refresh_token and client_credentials.
//     2. clientModel(): used for client_credentials only. 
const provider: OAuthProvider = new OAuthSqlProvider(sqlInterface);

// Then, we would instantiate the OAuth2Server using the model we prefer.
return new OAuth2Server({
    model: provider.userModel(getUserInteractor, loginUserInteractor),
    accessTokenLifetime: 60 * 60,
    allowBearerTokensInQueryString: true,
});
```

Link to [`OAuthProvider`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/oauth.provider.ts).
Link to [`OAuthSqlProvider`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/oauth.sql.provider.ts). Note this class requires in the constructor an [`SQLInterface`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/core/src/data/sql.interface.ts), which there is at this moment one implementation in *@mobilejazz/harmony-typeorm* [`TypeORMSQLInterface`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/typeorm/src/typeorm.sql.interface.ts) class .

The `clientModel()` method has no parameters. However, the `userModel()` method has two parameters:

1.  `getUserInteractor`, of type [`GetOAuthUserInteractor`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/domain/interactors/get-oauth-user.interactor.ts), an interface defined in the library where the developer must provide an implementation to perform a fetch of a user object given a userId (string) stored in the oauth database.

2. `loginUserInteractor`, of type [`LoginOAuthUserInteractor`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/domain/interactors/login-oauth-user.interactor.ts), an interface defined in the library where the developer must provide an implementation to perform a user login (given username + password, return a user or an error.

The `User` entity, defined in the developer project, must implement the [`OAuthUser`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/domain/oauth-user.model.ts) interface, which has only one method `oauthId(): string`, in which the user Id must be returned.

Now we have the `OAuth2Server` instance configured and ready to go. How to use it now?

## 2. Using the `OAuth2Server` instance

There are two major usages of the `OAuth2Server` instance:

### 1. Performing an authentication

In this case, a new endpoint must be defined, typically being a *POST* at */auth/token*. For this purpose, the library has a specific interactor called [`AuthControllerInteractor`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/domain/interactors/auth-controller.interactor.ts), which accepts per input the request and response builder of the endpoint. The interactor will take care of unwrapping the request, formatting it accordingly to the `OAuth2Server` requirements and pass it to it. Then, once the request has been processed, it will build the response. 

As an example of usage, a Nest controller would be like:

```typescript
@Controller('auth')
export class AuthController {
    constructor(
        @Inject('AuthControllerInteractor')
        private readonly authInteractor: AuthControllerInteractor,
    ) {}
    @Post('/token')
    login(@Req() request: any, @Res() response: any) {
        this.authInteractor.execute(request, response);
    }
}
```

### 2. Securing endpoints

This is typically achieved by **Guards**. In this case, the library offers an interactor that contains all the logic the guards needs. This is the [`OAuth2GuardInteractor`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/domain/interactors/oauth2-guard.interactor.ts). 

Therefore, writing a guard is as easy as shown:

```typescript
@Injectable()
export class OAuth2Guard implements CanActivate {
    constructor(
        @Inject('OAuth2GuardInteractor')
        private readonly oauthGuard: OAuth2GuardInteractor,
    ) {}
    async canActivate(context: ExecutionContext): Promise<boolean> {
        return this.oauthGuard.execute(context);
    }
}
```

Then, an endpoint can be secured as easy as doing `@UseGuard(OAuth2Guard)`

## 3. Defining the SQL Database

The library will require a SQL connector. As listed above, in this case we can use the [`TypeORMSQLInterface`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/typeorm/src/typeorm.sql.interface.ts) class. However, the SQL database for the OAuth must still be defined.

To accomplish this, right now the only way of doing this is to manually copying and executing the SQL directives defined in the file [*packages/nest/src/oauth/data/datasource/oauth.sql*](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/data/datasource/oauth.sql).

## 4. Example of usage of the `OAuth2Server`

Find [this repository](https://github.com/pedroetb/node-oauth2-server-example) that explains in detail how to use the `OAuth2Server`. However, find below some examples as a fast guide.

First of all, all authentication requests must include the `Authorization` HTTP header: `Basic <BASE64_ENCODED_APPLICATION_SECRET>`, where `BASE64_ENCODED_APPLICATION_SECRET` is the base 64 encoding of the string `client_id:client_secret`. The *client_id* and *client_secret*.  For example, using *client_id* := *application* and *client_secret* := *secret*, we would have `Basic YXBwbGljYXRpb246c2VjcmV0`.

### 1. Authenticate by password

Send a *POST* with the following body:
```json
{
    "grant_type": "password",
    "username": "john@doe.com",
    "password": "aaa123",
    "scope": ["word1", "word2", "word3"]
}
```
The `scope` is optional.

### 2. Authenticate by refresh token

Send a *POST* with the following body:
```json
{
    "grant_type": "refresh_token",
    "refresh_token": "THE_REFRESH_TOKEN"
}
```

### 2. Authenticate by client credentials

Send a *POST* with the following body:
```json
{
    "grant_type": "client_credentials"
}
```
Note the *client_id* and *client_secret* are defiend in the `Authorization` HTTP header.

**Comment by vilanovi** [comment]
Some actions to keep in mind:

1. Move the documentation listed above to the harmony-reference
2. Have the whole system reviewed by you guys, and give feedback. 

Some things that pop in my mind, is that currently the library is dependent on *Nest*, and this is something we might be able to remove (which makes it super nice as it would be reusable in any TS project). Mostly, both [`AuthControllerInteractor`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/domain/interactors/auth-controller.interactor.ts) and [`OAuth2GuardInteractor`](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/domain/interactors/oauth2-guard.interactor.ts) have *Nest* dependencies. If we could remove them, we would be completely decoupled from *Nest*!

**Comment by doup** [comment]
I think @lucianosantana would be better reviewing this.

**Comment by joselufo** [comment]
It's pretty complex to do a review right now but I'll try to give my comments here:

- `OAuth2UserModel` class contains commented code that it's not necessary, so it's just better to remove it. [link](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/application/oauth2.user.model.ts)

- `OAuth2BaseModel` contains commented code that it's not necesary, even if it's OPTIONAL in the comment we should remove as we have GIT to take a look in the future if needed. [link](https://github.com/mobilejazz/harmony-typescript/blob/develop/packages/nest/src/oauth/application/oauth2.base.model.ts)

- `DeleteOAuthTokenInteractor` we should return and error if delete fails as we are hiding a potential issue if something couldn't be remove it [link](https://github.com/mobilejazz/harmony-typescript/blob/040c5e7280b9758f026336a8a0e38338a621a7dc/packages/nest/src/oauth/domain/interactors/delete-oauth-token.interactor.ts#L17-L19)

It's pretty solid and well organised from my point of view, besides my three small comments I would say that it's ok to put it and try it. 

All OK for me

**Comment by vilanovi** [comment]
Lets then resolve this issue, as it's already being used in 2 client projects, and add being added in a third soon. 

I moved your feedback to issues Jose:

- https://github.com/mobilejazz/harmony-typescript/issues/22
- https://github.com/mobilejazz/harmony-typescript/issues/23
