### ISSUE TITLE
Remove deleteAll

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-typescript#7]
- Move logic from `deleteAll` to `delete`
- Make `deleteAll` call `delete`
- Mark `deleteAll` deprecated in both `DataSource` and `Repository`
- Mark `DeleteAllInteractor` deprecated

**Comment by doup** [comment]
@vilanovi I'm going to base these changes on the Kotlin PR: https://github.com/mobilejazz/harmony-kotlin/pull/14/files OK?

Btw, isn't better to directly remove the methods instead of adding a deprecation exception? This way we'll catch the errors on build-time.

**Comment by joselufo** [comment]
Yes and No because harmony-kotlin is widely used in several projects so breaking all those projects is not an option. 

Also, the refactor is not only changing the deleteAll() to delete() method because we need to check the implications in every project to do a proper refactor.

**Comment by doup** [comment]
I've created a PR, see #19.
