### ISSUE TITLE
Remove `AbstractLogger` and make `Logger` abstract

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#84]
We could just make `Logger` abstract and remove the `AbstractLogger`. This way we can directly use `Logger` in Angular/Nest instead of using `AbstractLogger` for the providers.

**Comment by joselufo** [comment]
@doup we should not be using the `AbstractLogger` and just use the `Logger`. It's again the same problem already described in the PR -> #87

**Comment by orioljp** [comment]
This issue has been moved to Asana.
https://app.asana.com/0/1109863238977521/1203172481263555/f
Closing it.
