### ISSUE TITLE
Repurpose `DataSource/Repository` base interface to `DataSource<T>/Repository<T>` get/put/delete type aliases

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#88]
### See agreed proposal: https://github.com/mobilejazz/harmony-typescript/issues/88#issuecomment-1264303423

--- 

**Original Message:**

We have an **empty** base `Repository` interface which all three repositories implement. On a provider is not very useful as the generic interactors will complain that the provided repository doesn't implement the interface… so something like this doesn't work:

```typescript
const repo: Repository = ...;
const put = new PutInteractor(repo);
```

Instead, we need to do this:

```typescript
const repo: GetRepository<MyModel> & PutRepository<MyModel> = …;
const put = new PutInteractor(repo);
```

Do we really need `Repository`?
Maybe we need some helper types that join these? Something like: `GetPutRepository<MyModel>`, `FullRepository<MyModel>`…

**Comment by orioljp** [comment]
@doup I've never seen the need of generate a repository as a generic one like you're proposing. The provider defines the specific repository that is being used. `SingleDataSurceRepository`, `GetRepositoryMapper`, .... all these implementations implement one or all the interfaces.

Could you show an example of this need?

**Comment by joselufo** [comment]
@doup we only have it in harmony-swift because it allows us to not provide the 3 different repositories or data sources in the constructor thanks to a swift generic feature. 

Here you [have an example of being used in harmony-swift](https://github.com/mobilejazz/harmony-swift/blob/develop/Sources/Harmony/Data/Repository/CacheRepository.swift) in the cache repository. We are providing one instance type for the main and another for the cache datasources.

As we can't do it on kotlin, we do not have that interface created in harmony-kotlin. 

I would suggest removing the interface from the code base as it's not useful. 

@doup or @orioljp can you take care?

**Comment by doup** [comment]
I suggest we repurpose it to the following:

```ts
type DataSource<T> = GetDataSource<T> & PutDataSource<T> & DeleteDataSource;
type Repository<T> = GetRepository<T> & PutRepository<T> & DeleteRepository;
```

In a provider, instead of using a concrete type (e.g. `RepositoryMapper<T, U>`) we can use this type instead: `Repository<T>`. We have the same exact issue with the `DataSource` type. Instead of listing all get/put/delete that a datasource needs to implement we can just `class XYZ implements DataSource<T>`.

--- 

@orioljp this is an example: c004ebd8b4c616e4623f1b6c5b1eab9f2d29f3d2

- In that commit we create a `getUserRepository()` method
- The return type has to be either:
    - `RepositoryMapper<T, U>`
    - `GetRepository<UserModel> & PutRepository<UserModel> & DeleteRepository`

I think the second option is the correct one. If we repurpose `Repository`, we could just express the return type as `Repository<UserModel>`.

**Comment by doup** [comment]
Btw, we could also add the following helper types (same applies for `DataSource`):

- `GetPutRepository<T>`
- `GetDeleteRepository<T>`
- `PutDeleteRepository<T>`

So we would have:

- `GetRepository<T>`
- `PutRepository<T>`
- `DeleteRepository`
- `GetPutRepository<T>`
- `GetDeleteRepository<T>`
- `PutDeleteRepository<T>`
- `Repository<T>`

**Comment by joselufo** [comment]
The type for the `DataSource<T>` and `Repository<T>` makes sense as it's replicating what we did in swift. 

Nevertheless, applying the same concept for all types of combinations is overkill, and it's already complex to explain things to the team, so adding more wrapper types will be more confusing.

**Comment by lucianosantana** [comment]
Sorry for joining late. Only after getting notified about the PR, I've noticed the discussion.

What if we do something like ?

```
type Repository<T> = (GetRepository<T> & PutRepository<T> & DeleteRepository) 
| (GetRepository<T> & PutRepository<T>) 
| (GetRepository<T> & DeleteRepository) 
| (PutRepository<T> & DeleteRepository) 
| GetRepository<T> 
| PutRepository<T>
| DeleteRepository;
```

**Comment by doup** [comment]
@lucianosantana @joselufo  I don't think this is a good idea. I see two problems:

1. By using an union we can't use the type as an interface, so no more `class XYZ implements Repository<T>`. This is not possible because TypeScript doesn't know which of the interfaces you want to implement.
2. Similarly, when you get a `Repository<T>` value, you might be getting a full Get+Put+Delete implementation… or just a Delete one. Since none of the methods is common to all the union types you need to narrow the type before using the value (e.g. `if ('getAll' in value) { /* now is narrowed to all the ones that impl Get */ }`).

[See TS Playground example:](https://www.typescriptlang.org/play?#code/PTAEBUE0AUFEGUBQBjANgQwM6dARQK4CmATgJ6gDeAvihtqAPIAOJ6ALgJYD2AdpTYkIAPJl2JtQHHmxIAzdMkKgA4oTYAlQqMwc2Y0gB5wAPkqJQF0AHM1ALlAAKAI5Ey9giVIAaUFxbF2bh57ZlZOXgBKUABeU2hiLgBbDkxCI2MAbnNLGzYAQVRUe2dXUndSnz8woJD-QMiYuITk1KMAbQBdTMQBYVFxSWk5BSVofA0tLh09MnSzS1AmceKAN3RUIntwUAAfUHweABNCWSlCQ58XT3LPSrrw4MZ7oKjY0HiklLSTLIWl-MKq3WREwW06u32RxOZwuoCubjwFV8z14tWqDTeHxa3063V6IjEEikMmI8kUoAAIoRUGpCJptLp9PNLMcaTJivCyojbsj0Y9QgEHq8mp9WisuBxDnjEIg2KQWKB6VNGbMTDFQNkLHtVBMGTNDGqAGTvcZK6b6ObGqlsumTc1kTUQnVmlUG0zGsa65X69KO7VqF0+o2U6m0wP6P0mr32t2gK2hmThh0Lf3R11zSOepNuyPWsN211ZRAgUAASQAstAADJINBYHAAVVSxH4MpLdfoTZISskiSYNMShGkOGzBi7xFMFFAJYAhHP3uoGAAhKuwcugACM9gbPCCOGQ6B4AHIJAAjJT4VKHUBYQYkslKW+6I84HhcCRoQjoFsAdwAFhwyB-r4sigGwf5KHKLCvoQ5w4HooDnr2-aEIOQyHLQ9agOOPYcH2A5DmwODOgWPrjsYPhZqRFrkT4eaJtRZDMhYSynqggE3pgpA8Mg1hqCU1zcmQXhVIKNRPHyET2FiXxjs2k6OgsxBqPgxB8DwhA-thzYOBEvyWAIfz4GxHFYNxvG5AUqACQiHjCaJ9T8iiPBSe8zSyeOuLMQsoDKWwql8G0GlaeOukdPpFiGZYrHsbxZk8Ys4wOGsGyENuzY7AcxynBpFycjc9nOWiYmRNJ7mtOR3lKSpamgMF2kkLpEWgFFLHGbFnHmYlALWSlILpSQnSZVCOXnF4+VCd4DkPMVjmuTJFXNl5FCKZYfkBaAQWaQ1xBhc1rWJSZcVcQlrK0jZXJ2VNRUSSVLllaKaTipKCk+WtNU8PtPQyh2xFqOOmClkMATIDM3nILwmBsMQ+Cg2IDirSxxAcGsMi+V+hy8Kg5CXt2kz2KOtEagsUTUDKRlHZ1CXCIQyDjIQukPdicmDV0VXvf5tXgSkAB0uPEEqPOWYUTXTmAc4zguy6ruuABM9gAOpKBp5xgVwdXfgkWngZB8pKOeshiBeOg8FYkhsJLSugMkVh-meSi5Jwps3ioagANSem79G2nqTJiKAABWl4SOgIY2tmjo0AIv2gPASSEB8KySiQ3lMMjqMO-9zZKoziqMYYlUrW9FjrbV9U4ZMTWR+T0Xp+wmdsADuc6gDQMkgoYNF8XEM8FD6OiOq3OYELWd46IVfF+jnPqdtLfNoDwMd-DymiHp1dUEAA)
1. Problem 1: Line 31.
2. Problem 2: Line 60.

---

**How were you thinking to use this union type?** As an alternative, maybe we can reconsider the addition of these?

- `GetPut*<T>`
- `GetDelete*<T>`
- `PutDelete*<T>`

**Comment by lucianosantana** [comment]
For the record, I've discussed with @doup and the "catch all" union type wouldn't be really helpful, as it gives no assurance about the expected methods to be implemented, forcing us to do some narrowing to use it.

The motivation for my suggestion was that I find confusing using the name "Repository" only for the case that implements all 3 types of Repository. While, for example, a PutRepository in this case wouldn't be of type Repository. 

But we actually have this pattern in other places. `SingleDataSourceRepository` which implements Get, Put and Delete, while  `SingleGetDataSourceRepository` implements only Get. Same for RepositoryMapper. It's not the most intuitive IMO, but once you learn it you just get used to it.

The alternative would be to write union specific types, without any wrapper type. But this would be too verbose and less efficient. 

So in the end, I'm convinced to use it this way to be consistent with the rest of the code base.
