### ISSUE TITLE
Add `UnreachableCaseError` utility error in `harmony-core`

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#89]
This utility error is handy to express exhaustive `switch` statements.

This is the utility error:

```typescript
export class UnreachableCaseError extends Error {
    constructor(val: never) {
        super(`Unreachable case: ${JSON.stringify(val)}`);
    }
}
```

And this is how you use it:

```typescript
switch (type) {
    case 'foo':
        return doSomething();
    default:
        throw new UnreachableCaseError(type);
}
```

Since `val` is `never` the switch branch should never be reachable otherwise TS will error. This ensures that all the cases are handled.

**Comment by joselufo** [comment]
@doup Why not directly create a PR instead of just opening an issue?

Nevertheless, I would say that if you need to use the `UnreachableCaseError` error, it's a sign of code smell because you should know why didn't reach it? and if you know the why better to have a specific error for the case.

**Comment by doup** [comment]
I was working on the strict stuff and didn't want to change to change context, even if it's for such a small PR. Opening an issue was faster than stashing, etc.

Anyway, I don't see how this is a code smell. The purpose of this pattern is to add a safeguard for future changes. Switches are non-exhaustive; so the idea is that if you add a new enum variant it'll force you to handle it.

Maybe you're missing [the `never` type](https://www.typescriptlang.org/docs/handbook/2/functions.html#never) here. If the `never` is reached (which should never happen) this produces a compile time error, not a runtime one. [See the following example, follow the top instructions.](https://www.typescriptlang.org/play?#code/PTAEEYEpQZQUzqALgCwIZOSuAnRa8A7AckzUIE9QBjAewFsAHASwBsNnbDRcdacAzgCgQoAEzQAqoTr16cQplbNCicABYAdKABytAO6gAzOFAAzNGwEAaUGgGgABgBM4FgK6skj0ACMc5NQooAIotJ7OfoiOqgBuuD54aEFwziJgRlIyDPKK4gAcALRiAJy2qIi8-KDOzAJojHAEDvZ2rKxYiP6B2C14oOiEzqypQkLU7AIO0klBaL4jAML2cACiOHw4PAAeSArODuuboADeQqAXNFwCSDju1Ej8ABSxaKwAXKBxuNBnl-8hdyNHBPRwzJpzBaIagrT4AEhOACkYAB5HSaG44FQAc2YZgoLzekAAvo5IABuc6XYlCGlCBTueigVbxRQAFQojVOVIuADFaLRQABeUDEMwC4jWHmgABCBGFot8BEl0tEcoAXgriEr1ZLQKIADxC42gSQ6RYogCy1tWOjZoDZAAkAJIwUAAGWdOlWtLGKj2OAs1EQlooLIUmD+lyQnLgn3D7NjlLpdEIN1A9DDrKQn1DCcwIpOyFj8ezHMamn5guJlKEAn0zCQQVAT0z+c0Mcav2lMIEiHz5bglYF72l-38TQA1pT-r3+2XY5o5ThRwDLhO0NPVWA58yFxWNavLqJx0kt-9XB4vEe16g+IZVIZwcl0FDln2js829mO7GKbSgA)

Another use case for the `never` type would be to express a function that never returns:

```typescript
function infiniteLoop(): never {
    while (true) {
    }
}
```

**Comment by joselufo** [comment]
@doup, thanks for the clarifications; I understand it better. I was not aware of the `never` type. It's the same concept as the `Nothing` type in kotlin --> https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-nothing.html

I do not see any problem with adding it to the core library. 

Leaving the final decision to @orioljp

**Comment by orioljp** [comment]
I totally agree with this change, let's keep this issue
