### ISSUE TITLE
Add "type predicates"/guards to queries to help narrow down types?

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#90]
On `strict` mode, even if we use `instanceof x` TS doesn't solve the generic.

See for example `IdQuery`, if we check with `instanceof` without generic parameter, it casts `query` to `IdQuery<any>`; this is reasonable:

![image](https://user-images.githubusercontent.com/188612/178110510-942efaeb-77fc-4a1b-abce-ca17f93510f6.png)

But, if we check with `instanceof IdQuery<string | number>` it stills casts to `IdQuery<any>`. This is somewhat surprising, although reasonable as generics don't exist at runtime and there is no way for `instanceof` to have checked the generic:

![image](https://user-images.githubusercontent.com/188612/178110776-33694f2e-1ead-4577-b643-3245c3944073.png)

Although, with a [type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) this is solved by using a default generic, in this case `IdQuery<string | number>`:

![image](https://user-images.githubusercontent.com/188612/178110870-81e7c6bb-9a90-4b68-a4da-9aa887f65d62.png)

![image](https://user-images.githubusercontent.com/188612/178110940-6c7b5989-68c5-403e-8509-14022aff87f2.png)

---

The alternative is just type cast the inner `id: any` property, maybe this is good enough:

![image](https://user-images.githubusercontent.com/188612/178111029-a680b4e4-bb87-4688-bcf5-a4ee36f030c9.png)

**Comment by joselufo** [comment]
@doup I think it makes more sense for the inner `id: any` property because otherwise, we are adding hard constrains in the `IdQuery` as the `T` value could be even a complex model.

What do you think?

**Comment by doup** [comment]
Well, we already have the constraint in the generic… but maybe that's wrong? We should change it to `anything that implements "toString"`?

![image](https://user-images.githubusercontent.com/188612/183367769-6b7353e3-1dab-47eb-aad7-a1fae0556aed.png)

---

Anyway, in the end, to make TS strict-mode happy I "casted" with `const id: string | number = query.id;` (which won't be correct if we change the constraint). I'll close this for now. **But if the constraint is wrong we need to open another issue.**

**Comment by joselufo** [comment]
@doup, that's already wrong as we should not be adding to `T` the constraint to `number` or `string`. 

It should not be constrained by any type and we can do the checks in the constructor. 

See the following implementations:
* [harmony-swift](https://github.com/mobilejazz/harmony-swift/blob/e47fb8fd68696486637dfc825dcb6dd12b329e7d/Sources/Harmony/Data/Query/Query.swift)
* [harmony-kotlin](https://github.com/mobilejazz/harmony-kotlin/blob/c6822c2f562975053a8d6623710e7118b5abaf23/harmony-kotlin/src/commonMain/kotlin/com.harmony.kotlin/data/query/Query.kt)
