### ISSUE TITLE
Add extra pagination wrappers

### ISSUE THREAD

**Issue by doup** [mobilejazz/harmony-typescript#91]
We currently have [offset/limit based pagination](https://github.com/mobilejazz/harmony-typescript/blob/master/packages/core/src/data/pagination.ts), but we don't contemplate cursor based ones (e.g. Firebase). It would be useful to express other types of paginators in case we want to eventually have auto-generated backoffices. See:

[Paginating Requests in APIs. Should all APIs use Cursor-based pagination? Learn the different pagination strategies available and their advantages and disadvantages](https://ignaciochiazzo.medium.com/paginating-requests-in-apis-d4883d4c1c4c)

**Comment by joselufo** [comment]
@doup you are right, they are not contemplating it because we didn't need it yet. 

`Pagination<T>` is generic enough to support other types of pagination just extending it.

If you agreed, we could close the issue as till we don't need it, we won't implement it.

@doup what do you think?

**Comment by doup** [comment]
I actually had to create a similar paginator on a Firebase project; but I didn't gave it too much thought and probably needs to be revisited to see if it models correctly other cursor based data-sources.

I would leave the issue here, as a reminder for when we want to look into back-office generation.

**Comment by orioljp** [comment]
This issue has been moved to Asana.
https://app.asana.com/0/1109863238977521/1203172481263571/f
Closing it.
